language: python

python:
- '3.6'

notifications:
  slack: qed-epa:FnRva7RtXZLlczmpxShtokg

before_install:
- openssl aes-256-cbc -K $encrypted_47198b22a71b_key -iv $encrypted_47198b22a71b_iv
  -in ./tests/smoketest_secrets.py.enc -out ./tests/smoketest_secrets.py
  -d
- chmod +x travis_build.sh

install: "./travis_build.sh"

script:
- pytest ./tests